CREATE TABLE [DBO].[USERS](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[USERNAME] [VARCHAR](256) NOT NULL,
	[EMAIL] [VARCHAR](256) NOT NULL,
	[DESCRIPTION] [VARCHAR](256) NOT NULL,
	[CITY] [VARCHAR](256) NOT NULL,
	[STREET] [VARCHAR](256) NOT NULL,
 CONSTRAINT [PK__USERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
 )
) ON [PRIMARY]
GO

INSERT INTO USERS (USERNAME, EMAIL, CITY, DESCRIPTION, STREET)
VALUES ('andrei', 'andrei@yahoo.com', 'iasi', 'some user', 'street 1');

INSERT INTO USERS (USERNAME, EMAIL, CITY, DESCRIPTION, STREET)
VALUES ('dan', 'dan@yahoo.com', 'iasi', 'some user', 'street 2');

INSERT INTO USERS (USERNAME, EMAIL, CITY, DESCRIPTION, STREET)
VALUES ('gigi', 'gigi@yahoo.com', 'vaslui', 'some user', 'street 2');